### ISSUE TITLE
plugin install hides all posts

### ISSUE THREAD

**Issue by grzbielok** [jwplayer/wordpress-plugin#1] opened 2015-12-18 10:21 UTC
We tried the plugin and found that after installing it, all our posts were hidden from the post dashboard, even though the count was correct: 

![image](https://cloud.githubusercontent.com/assets/1083614/11894725/65131dbe-a579-11e5-8e4f-8a2fcb2aa0bb.png)

Deinstalling the plugin fixed the problem.

**Comment by rmnl** [comment] 2016-01-05 13:30
This is a known issue and we've been unable to reproduce it in our own testing environment, which makes it hard to make a fix.

The list does work after you run the migration.

Could you also share some more information about your environment.

**Comment by rmnl** [comment] 2016-01-12 14:26
Will close this due to lack of info. Please reopen if someone is able to give details on how to reproduce this.

**Closed by rmnl** 2016-01-12 14:26 UTC
